In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import nfl_data_py as nfl

RAW_DIR = Path("../data/raw")
PROCESSED_DIR = Path("../data/processed")

RAW_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

YEARS = list(range(2011, 2021))

In [2]:
draft = nfl.import_draft_picks(YEARS)

draft.head()

,season,round,pick,team,gsis_id,pfr_player_id,cfb_player_id,pfr_player_name,hof,position,...,pass_ints,rush_atts,rush_yards,rush_tds,receptions,rec_yards,rec_tds,def_solo_tackles,def_ints,def_sacks
8832,2011,1,1,CAR,00-0027939,NewtCa00,cam-newton-1,Cam Newton,False,QB,...,123.0,1118.0,5628.0,75.0,3.0,68.0,1.0,NaN,NaN,NaN
8833,2011,1,2,DEN,00-0027940,MillVo00,von-miller-1,Von Miller,False,LB,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,462.0,2.0,138.5
8834,2011,1,3,BUF,00-0027941,DareMa00,marcell-dareus-1,Marcell Dareus,False,DT,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,255.0,NaN,37.5
8835,2011,1,4,CIN,00-0027942,GreeA.00,aj-green-1,A.J. Green,False,WR,...,0.0,11.0,93.0,0.0,727.0,10514.0,70.0,NaN,NaN,NaN
8836,2011,1,5,ARI,00-0027943,PetePa00,patrick-peterson-1,Patrick Peterson,False,DB,...,0.0,7.0,34.0,0.0,10.0,64.0,0.0,571.0,36.0,4.0

In [ ]:
draft.columns

Index(['season', 'round', 'pick', 'team', 'gsis_id', 'pfr_player_id',
       'cfb_player_id', 'pfr_player_name', 'hof', 'position', 'category',
       'side', 'college', 'age', 'to', 'allpro', 'probowls', 'seasons_started',
       'w_av', 'car_av', 'dr_av', 'games', 'pass_completions', 'pass_attempts',
       'pass_yards', 'pass_tds', 'pass_ints', 'rush_atts', 'rush_yards',
       'rush_tds', 'receptions', 'rec_yards', 'rec_tds', 'def_solo_tackles',
       'def_ints', 'def_sacks'],
      dtype='str')

In [ ]:
draft.to_csv(RAW_DIR / "draft_picks.csv", index=False)

In [ ]:
draft_values = nfl.import_draft_values(range(1,263))  # Not year specific

draft_values

     pick  stuart  johnson     hill   otc    pff
0       1    34.6     3000  1000.00  3000  1.135
1       2    30.2     2600   717.17  2635  1.099
2       3    27.6     2200   514.33  2421  1.063
3       4    25.8     1800   490.52  2270  1.027
4       5    24.3     1700   467.81  2152  0.991
..    ...     ...      ...      ...   ...    ...
257   258     0.0        0     1.08    76  0.047
258   259     0.0        0     1.06    74  0.047
259   260     0.0        0     1.04    72  0.046
260   261     0.0        0     1.02    70  0.046
261   262     0.0        0     1.00    68  0.046

[262 rows x 6 columns]

In [14]:
draft_values.columns

Index(['pick', 'stuart', 'johnson', 'hill', 'otc', 'pff'], dtype='str')

In [15]:
draft_values.to_csv(RAW_DIR / "draft_values.csv", index=False)

In [16]:
draft_av = draft[['pick', 'dr_av']]  # Options: 'w_av', 'car_av', 'dr_av'

draft_values_vs_av = draft_values.merge(
    draft_av,
    on="pick",
    how="left"
)

draft_values_vs_av.head()

   pick  stuart  johnson    hill   otc    pff  dr_av
0     1    34.6     3000  1000.0  3000  1.135  107.0
1     1    34.6     3000  1000.0  3000  1.135   72.0
2     1    34.6     3000  1000.0  3000  1.135   56.0
3     1    34.6     3000  1000.0  3000  1.135   38.0
4     1    34.6     3000  1000.0  3000  1.135   54.0

In [17]:
draft_values_vs_av.to_csv(RAW_DIR / "draft_values_vs_av.csv", index=False)

In [18]:
combine = nfl.import_combine_data()
combine.head()

,season,draft_year,draft_team,draft_round,draft_ovr,pfr_id,cfb_id,player_name,pos,school,ht,wt,forty,bench,vertical,broad_jump,cone,shuttle
0,2000,2000.0,New York Jets,1.0,13.0,AbraJo00,NaN,John Abraham,OLB,South Carolina,6-4,252.0,4.55,NaN,NaN,NaN,NaN,NaN
1,2000,2000.0,Seattle Seahawks,1.0,19.0,AlexSh00,shaun-alexander-1,Shaun Alexander,RB,Alabama,6-0,218.0,4.58,NaN,NaN,NaN,NaN,NaN
2,2000,2000.0,Kansas City Chiefs,6.0,188.0,AlfoDa20,NaN,Darnell Alford,OT,Boston Col.,6-4,334.0,5.56,23.0,25.0,94.0,8.48,4.98
3,2000,NaN,NaN,NaN,NaN,NaN,NaN,Kyle Allamon,TE,Texas Tech,6-2,253.0,4.97,NaN,29.0,104.0,7.29,4.49
4,2000,2000.0,Carolina Panthers,1.0,23.0,AndeRa21,NaN,Rashard Anderson,CB,Jackson State,6-2,206.0,4.55,NaN,34.0,123.0,7.18,4.15

In [19]:
combine.groupby('season').size()

season
2000    321
2001    321
2002    320
2003    319
2004    335
2005    331
2006    328
2007    326
2008    330
2009    327
2010    326
2011    329
2012    324
2013    332
2014    333
2015    322
2016    332
2017    327
2018    336
2019    336
2020    337
2021    464
2022    324
2023    319
2024    321
2025    329
2026    319
dtype: int64

In [20]:
combine['season'].min(), combine['season'].max()

(np.int32(2000), np.int32(2026))